---
driver:
  name: vagrant
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: /Users/curtstewart/.ssh/id_rsa

platforms:
- name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[build-essential::default]
      - recipe[fog_cloud::default]
      - recipe[fog_cloud::test]
    attributes:
      openstack_username: <%= ENV['OS_USERNAME'] %>
      openstack_api_key:  <%= ENV['OS_PASSWORD'] %>
      openstack_auth_url:  <%= ENV['OS_AUTH_URL'] %>/tokens
      openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
      build_essential:
        compiletime: true
